# Site settings
title: NodeGit
description: Asynchronous native Node bindings to libgit2
url: "http://nodegit.org"
date_format: "ordinal"
current_nodegit_version: 0.11.9
other_nodegit_versions:
  - HEAD 
  - 0.11.8
  - 0.11.7
  - 0.11.6
  - 0.11.5
  - 0.11.4
  - 0.11.3
  - 0.11.2
  - 0.11.1
  - 0.11.0
  - 0.10.0
  - 0.9.0
  - 0.8.0
  - 0.7.0
  - 0.6.3
  - 0.6.2
  - 0.6.1
  - 0.6.0
  - 0.5.0
  - 0.4.1
  - 0.4.0
  - 0.3.3
  - 0.2.7

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [tables, no_intra_emphasis, autolink]
highlighter: pygments
permalink: pretty
exclude: ["node_modules","generate","package.json","README.md", "CNAME", "Gemfile", "Gemfile.lock"]
