# Site settings
title: NodeGit
description: Asynchronous native Node bindings to libgit2
url: "http://nodegit.org"
date_format: "ordinal"
current_nodegit_version: 0.3.0
other_nodegit_versions:
  - HEAD
  - 0.2.7

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [tables, no_intra_emphasis, autolink]
highlighter: pygments
permalink: pretty
exclude: ["node_modules","generate","package.json","README.md"]
